spring.application.name=musicify-api

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JWT Configuration
jwt.secret=super-secret-key-that-is-at-least-32-bytes-long
jwt.expiration=86400000
